set_property PACKAGE_PIN V17 [get_ports {ta}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ta}]
set_property PACKAGE_PIN V16 [get_ports {tb}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tb}]
set_property PACKAGE_PIN W16 [get_ports {tc}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tc}]
set_property PACKAGE_PIN W17 [get_ports {td}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {td}]
set_property PACKAGE_PIN W15 [get_ports {te}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {te}]
set_property PACKAGE_PIN V15 [get_ports {tf}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tf}]
set_property PACKAGE_PIN W14 [get_ports {tg}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tg}]
set_property PACKAGE_PIN W13 [get_ports {th}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {th}]		
	
	
set_property PACKAGE_PIN W7 [get_ports {a}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a}]
set_property PACKAGE_PIN W6 [get_ports {b}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b}]
set_property PACKAGE_PIN U8 [get_ports {c}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {c}]
set_property PACKAGE_PIN V8 [get_ports {d}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d}]
set_property PACKAGE_PIN U5 [get_ports {e}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e}]
set_property PACKAGE_PIN V5 [get_ports {f}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {f}]
set_property PACKAGE_PIN U7 [get_ports {g}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {g}]
set_property PACKAGE_PIN V7 [get_ports {h}]							
	set_property IOSTANDARD LVCMOS33 [get_ports {h}]



##-- anodes

set_property PACKAGE_PIN U2 [get_ports {a1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a1}]
set_property PACKAGE_PIN U4 [get_ports {a2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a2}]
set_property PACKAGE_PIN V4 [get_ports {a3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a3}]
set_property PACKAGE_PIN W4 [get_ports {a4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a4}]
	
set_property PACKAGE_PIN W2 [get_ports {i}]
	set_property IOSTANDARD LVCMOS33 [get_ports {i}]
set_property PACKAGE_PIN U1 [get_ports {j}]
	set_property IOSTANDARD LVCMOS33 [get_ports {j}]
set_property PACKAGE_PIN T1 [get_ports {k}]
	set_property IOSTANDARD LVCMOS33 [get_ports {k}]
set_property PACKAGE_PIN R2 [get_ports {l}]
	set_property IOSTANDARD LVCMOS33 [get_ports {l}]