#clock
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]

#timing indicator
set_property PACKAGE_PIN V7 [get_ports {ind}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ind}]


#seven-segment LED display
        set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
        set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
        set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
        set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
        set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
        set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
        set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
#disp
set_property PACKAGE_PIN U16 [get_ports {dispo[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[0]}]
set_property PACKAGE_PIN E19 [get_ports {dispo[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[1]}]
set_property PACKAGE_PIN U19 [get_ports {dispo[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[2]}]
set_property PACKAGE_PIN V19 [get_ports {dispo[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[3]}]
set_property PACKAGE_PIN W18 [get_ports {dispo[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[4]}]
set_property PACKAGE_PIN U15 [get_ports {dispo[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[5]}]
set_property PACKAGE_PIN U14 [get_ports {dispo[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[6]}]
set_property PACKAGE_PIN V14 [get_ports {dispo[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[7]}]
set_property PACKAGE_PIN V13 [get_ports {dispo[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[8]}]
set_property PACKAGE_PIN V3 [get_ports {dispo[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[9]}]
set_property PACKAGE_PIN W3 [get_ports {dispo[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[10]}]
set_property PACKAGE_PIN U3 [get_ports {dispo[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[11]}]
set_property PACKAGE_PIN P3 [get_ports {dispo[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[12]}]
set_property PACKAGE_PIN N3 [get_ports {dispo[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[13]}]
set_property PACKAGE_PIN P1 [get_ports {dispo[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[14]}]
set_property PACKAGE_PIN L1 [get_ports {dispo[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dispo[15]}]
#anode_out
        set_property PACKAGE_PIN U2 [get_ports {anode_out[0]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {anode_out[0]}]
        set_property PACKAGE_PIN U4 [get_ports {anode_out[1]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {anode_out[1]}]
        set_property PACKAGE_PIN V4 [get_ports {anode_out[2]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {anode_out[2]}]
        set_property PACKAGE_PIN W4 [get_ports {anode_out[3]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {anode_out[3]}]